[build]
  base = "/"
  command = "npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["server/src/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5000
  port = 8888 